export default {
  SOURCE_FETCH_ACTION: 'SOURCE_FETCH_ACTION',
  SOURCE_FETCH_START: 'SOURCE_FETCH_START',
  SOURCE_FETCH_SUCCESS: 'SOURCE_FETCH_SUCCESS',
  SOURCE_FETCH_FAIL: 'SOURCE_FETCH_FAIL',

  SOURCE_FETCH_MORE_ACTION: 'SOURCE_FETCH_MORE_ACTION',
  SOURCE_FETCH_MORE_START: 'SOURCE_FETCH_MORE_START',
  SOURCE_FETCH_MORE_SUCCESS: 'SOURCE_FETCH_MORE_SUCCESS',
  SOURCE_FETCH_MORE_FAIL: 'SOURCE_FETCH_MORE_FAIL',

  SET_CHARACTER_ACTION: 'SET_CHARACTER_ACTION'
}