export default {
  SOURCE_FETCH_ACTION: 'SOURCE_FETCH_ACTION',
  SOURCE_FETCH_START: 'SOURCE_FETCH_START',
  SOURCE_FETCH_SUCCESS: 'SOURCE_FETCH_SUCCESS',
  SOURCE_FETCH_FAIL: 'SOURCE_FETCH_FAIL',

  SOURCE_FETCH_MORE_ACTION: 'SOURCE_FETCH_MORE_ACTION',
  SOURCE_FETCH_MORE_START: 'SOURCE_FETCH_MORE_START',
  SOURCE_FETCH_MORE_SUCCESS: 'SOURCE_FETCH_MORE_SUCCESS',
  SOURCE_FETCH_MORE_FAIL: 'SOURCE_FETCH_MORE_FAIL',

  SET_CHARACTER_ACTION: 'SET_CHARACTER_ACTION',

  WATCHED_LOAD_ACTION: 'WATCHED_LOAD_ACTION',
  WATCHED_LOAD_START: 'WATCHED_LOAD_START',
  WATCHED_LOAD_SUCCESS: 'WATCHED_LOAD_SUCCESS',
  WATCHED_LOAD_FAIL: 'WATCHED_LOAD_FAIL',

  WATCHED_CHECK_ACTION: 'WATCHED_CHECK_ACTION',
  WATCHED_CHECK_START: 'WATCHED_CHECK_START',
  WATCHED_CHECK_SUCCESS: 'WATCHED_CHECK_SUCCESS',
  WATCHED_CHECK_FAIL: 'WATCHED_CHECK_FAIL',

  WATCHED_UNCHECK_ACTION: 'WATCHED_UNCHECK_ACTION',
  WATCHED_UNCHECK_START: 'WATCHED_UNCHECK_START',
  WATCHED_UNCHECK_SUCCESS: 'WATCHED_UNCHECK_SUCCESS',
  WATCHED_UNCHECK_FAIL: 'WATCHED_UNCHECK_FAIL',

  FAVORITES_LOAD_ACTION: 'FAVORITES_LOAD_ACTION',
  FAVORITES_LOAD_START: 'FAVORITES_LOAD_START',
  FAVORITES_LOAD_SUCCESS: 'FAVORITES_LOAD_SUCCESS',
  FAVORITES_LOAD_FAIL: 'FAVORITES_LOAD_FAIL',

  FAVORITE_ADD_ACTION: 'FAVORITE_ADD_ACTION',
  FAVORITE_ADD_START: 'FAVORITE_ADD_START',
  FAVORITE_ADD_SUCCESS: 'FAVORITE_ADD_SUCCESS',
  FAVORITE_ADD_FAIL: 'FAVORITE_ADD_FAIL',

  FAVORITE_DELETE_ACTION: 'FAVORITE_DELETE_ACTION',
  FAVORITE_DELETE_START: 'FAVORITE_DELETE_START',
  FAVORITE_DELETE_SUCCESS: 'FAVORITE_DELETE_SUCCESS',
  FAVORITE_DELETE_FAIL: 'FAVORITE_DELETE_FAIL'
}